package rex

import (
	"bytes"
	b64 "encoding/base64"
	"fmt"
	"testing"
	// "github.com/go-gl/mathgl/mgl32"
)

func TestDecodingHeader(t *testing.T) {

	b, err := b64.StdEncoding.DecodeString(rexBuffer)
	if err != nil {
		panic(err)
	}
	r := bytes.NewReader(b)

	d := NewDecoder(r)
	header, rex, err := d.Decode()

	if err != nil {
		t.Fatalf("TEST ERROR: %v", err)
	}
	if rex == nil {
		fmt.Println("rex file is nil")
	}

	fmt.Println(header)
}

// Base64 encoded test REX file
// Generated by base64 mesh.rex
const rexBuffer = `
UkVYMQEAAAAAAAIAVgAUAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAACQPAAAEAEVQU0cAAAAAAAAAAAAAAAADAAEAsAAAAAEAAAAAAAAAAAAAAAMAAAAAAAAA
AAAAAAAAAAABAAAAgAAAAKQAAACkAAAApAAAAKQAAAAAAAAAAAAAAAQAdGVzdAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAIA/AAAAAAAAAAAAAAA/AACAPwAAAAAAAAAAAQAAAAIAAAAFAAEARAAA
AAAAAAAAAAAAAACAPwAAAAAAAAAA/////////38AAIA/AAAAAAAAAAD/////////fwAAgD8AAAAA
AAAAAP////////9/AAAAAAAAgD8=
`
